
require('./assets/script/dialog/finishPop');
require('./assets/script/dialog/outPop');
require('./assets/script/dialog/pingFenPop');
require('./assets/script/dialog/quitPop');
require('./assets/script/dialog/setPop');
require('./assets/script/dialog/termPop');
require('./assets/script/load');
require('./assets/script/main');
require('./assets/script/prefeb/imgItem');
require('./assets/script/prefeb/newhand');
require('./assets/script/sala');
require('./assets/script/tool/AutoBind');
require('./assets/script/tool/gameControl');
require('./assets/script/tool/playroomData');
require('./assets/script/tool/resLoading');
require('./assets/script/tool/scrollTool');
require('./assets/script/tool/stockpileUtils');
require('./assets/script/tool/voiceUtils');
